spring.application.name=workshopmongo

spring.data.mongodb.uri=mongodb+srv://maria:teste123@google-cloud-webflux-mo.j6uuxaa.mongodb.net/?appName=google-cloud-webflux-mongo
spring.data.mongodb.database=workshop_mongo
